### PR TITLE
icons working

### PR DESCRIPTION
**Pull request by mjkkirschner**
adds some icons to the UI sample nodes to illustrate how icons can be added for these or ZT nodes. Should probably have more comments.

@ramramps @QilongTang @nonoesp

### CODE REVIEW

**Comment by Racel** [comment]
@mjkkirschner - can you please update the wiki with the additional examples?

**Comment by mjkkirschner** [comment]
@alfarok did you get a chance to look at this?

**Comment by alfarok** [comment]
@mjkkirschner seems like this would be very helpful for 3rd party devs migrating their packages to 2.0, especially if the protocol is different from 1.3

**Comment by alfarok** [comment]
@mjkkirschner I pulled this branch and built but don't see any icons when I load the `Dynamo Samples` package.  I see the `SampleLibraryUI.customization.dll` file in the package bin folder.  Are there any additional steps?

**Pull request closed without merging**
