### PR TITLE
Added CefSharp window example

### PR DESCRIPTION
**Pull request by cesarecaoduro**

### CODE REVIEW

**Comment by QilongTang** [comment]
@mjkkirschner @Amoursol Do we want to consider adding this in soon?

**Comment by Amoursol** [comment]
@QilongTang Happy to add from my end! The more examples the better.

**Comment by mjkkirschner** [comment]
I'm not so sure - this modifies the existing viewExtension sample in significant ways. It also complicates it.

I'm also not so sure we should encourage use of CEFSharp within our own samples.

If we were going to merge this, I would want to make it a separate sample that outlines the concerns and use cases for using CEF. This currently does not do that.

**Comment by Amoursol** [comment]
Fair call @mjkkirschner - will defer to your guidance on this one.

**Comment by mjkkirschner** [comment]
Hi @cesarecaoduro - thanks for this PR - I'm thinking it would be simpler for new users to come to grips with writing extensions if the examples were as straight forward as possible and built on each other in complexity, to that end I think

1. this example using CEF should be a different project/sample extension entirely from the other view extension.

theres also a couple other concerning bits:

* updating nunit - but nunit3 is not compatible with dynamos' test classes
* the chosen version of CEF will not work in Revit or Civil 3d.
* why add the x86 and x64 configs to every single project... Ideally we would only add the x64 config to a new project that references CEF.
* modification of the extension manifest makes it incompatible as a package (I think, have not tested)

**Pull request closed without merging**
